# Generated by Django 5.2.1 on 2025-05-28 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('ordered', 'Ordered'), ('sent', 'Sent'), ('activated', 'Activated'), ('expired', 'Expired'), ('opposed', 'Opposed'), ('failed', 'Failed'), ('deactivated', 'Deactivated'), ('canceled', 'Canceled')], default='not_submitted', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, choices=[('black', 'Black'), ('pink', 'Pink')], max_length=10, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
